ARG OS_VERSION=latest

FROM archlinux:${OS_VERSION}

RUN pacman -Sy --noconfirm \
        archlinux-keyring \
        python \
        python-pip \
        openssl \
        sudo \
        systemd \
        util-linux \
    && pacman -Syu --noconfirm \
    && rm -f /lib/systemd/system/systemd*udev* \
    && rm -f /lib/systemd/system/getty.target \
    && rm -rf /usr/lib/python3.12/EXTERNALLY-MANAGED \
    && locale-gen en_US.UTF-8

# Install ansible
RUN pip install ansible

# Install Ansible inventory file.
RUN mkdir -p /etc/ansible
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

# Fake initctl to launch services
COPY initctl_faker .
RUN chmod +x initctl_faker && rm -fr /sbin/initctl && ln -s /initctl_faker /sbin/initctl

VOLUME ["/sys/fs/cgroup", "/tmp", "/run"]
CMD ["/lib/systemd/systemd"]
