---
services:
  archlinux_latest:
    image: warpcode/molecule-archlinux:latest
    privileged: true
    cgroup: host
    build:
      context: ./
      dockerfile: ./Dockerfile.archlinux
      args:
        OS_VERSION: latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  archlinux_latest_desktop:
    image: warpcode/molecule-archlinux:latest_desktop
    privileged: true
    cgroup: host
    build:
      context: ./
      dockerfile: ./Dockerfile.archlinux
      args:
        OS_VERSION: latest
        DESKTOP_INSTALL: "1"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  debian_stable:
    image: warpcode/molecule-debian:stable
    privileged: true
    cgroup: host
    build:
      context: ./
      dockerfile: ./Dockerfile.debian
      args:
        OS_VERSION: stable
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  debian_stable_desktop:
    image: warpcode/molecule-debian:stable_desktop
    privileged: true
    cgroup: host
    build:
      context: ./
      dockerfile: ./Dockerfile.debian
      args:
        OS_VERSION: stable
        DESKTOP_INSTALL: "1"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  debian_unstable:
    image: warpcode/molecule-debian:unstable
    privileged: true
    cgroup: host
    build:
      context: ./
      dockerfile: ./Dockerfile.debian
      args:
        OS_VERSION: unstable
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  debian_unstable_desktop:
    image: warpcode/molecule-debian:unstable_desktop
    privileged: true
    cgroup: host
    build:
      context: ./
      dockerfile: ./Dockerfile.debian
      args:
        OS_VERSION: unstable
        DESKTOP_INSTALL: "1"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  debian_12:
    image: warpcode/molecule-debian:12
    privileged: true
    cgroup: host
    build:
      context: ./
      dockerfile: ./Dockerfile.debian
      args:
        OS_VERSION: 12
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  debian_12_desktop:
    image: warpcode/molecule-debian:12_desktop
    privileged: true
    cgroup: host
    build:
      context: ./
      dockerfile: ./Dockerfile.debian
      args:
        OS_VERSION: 12
        DESKTOP_INSTALL: "1"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  debian_11:
    image: warpcode/molecule-debian:11
    privileged: true
    cgroup: host
    build:
      context: ./
      dockerfile: ./Dockerfile.debian
      args:
        OS_VERSION: 11
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  debian_11_desktop:
    image: warpcode/molecule-debian:11_desktop
    privileged: true
    cgroup: host
    build:
      context: ./
      dockerfile: ./Dockerfile.debian
      args:
        OS_VERSION: 11
        DESKTOP_INSTALL: "1"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  fedora_latest:
    image: warpcode/molecule-fedora:latest
    privileged: true
    cgroup: host
    build:
      context: ./
      dockerfile: ./Dockerfile.fedora
      args:
        OS_VERSION: latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  fedora_latest_desktop:
    image: warpcode/molecule-fedora:latest_desktop
    privileged: true
    cgroup: host
    build:
      context: ./
      dockerfile: ./Dockerfile.fedora
      args:
        OS_VERSION: latest
        DESKTOP_INSTALL: "1"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  fedora_41:
    image: warpcode/molecule-fedora:41
    privileged: true
    cgroup: host
    build:
      context: ./
      dockerfile: ./Dockerfile.fedora
      args:
        OS_VERSION: 41
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  fedora_41_desktop:
    image: warpcode/molecule-fedora:41_desktop
    privileged: true
    cgroup: host
    build:
      context: ./
      dockerfile: ./Dockerfile.fedora
      args:
        OS_VERSION: 41
        DESKTOP_INSTALL: "1"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  fedora_40:
    image: warpcode/molecule-fedora:40
    privileged: true
    cgroup: host
    build:
      context: ./
      dockerfile: ./Dockerfile.fedora
      args:
        OS_VERSION: 40
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  fedora_40_desktop:
    image: warpcode/molecule-fedora:40_desktop
    privileged: true
    cgroup: host
    build:
      context: ./
      dockerfile: ./Dockerfile.fedora
      args:
        OS_VERSION: 40
        DESKTOP_INSTALL: "1"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  ubuntu_latest:
    image: warpcode/molecule-ubuntu:latest
    privileged: true
    cgroup: host
    build:
      context: ./
      dockerfile: ./Dockerfile.ubuntu
      args:
        OS_VERSION: latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  ubuntu_latest_desktop:
    image: warpcode/molecule-ubuntu:latest_desktop
    privileged: true
    cgroup: host
    build:
      context: ./
      dockerfile: ./Dockerfile.ubuntu
      args:
        OS_VERSION: latest
        DESKTOP_INSTALL: "1"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  ubuntu_25_04:
    image: warpcode/molecule-ubuntu:25.04
    privileged: true
    cgroup: host
    build:
      context: ./
      dockerfile: ./Dockerfile.ubuntu
      args:
        OS_VERSION: 25.04
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  ubuntu_25_04_desktop:
    image: warpcode/molecule-ubuntu:25.04_desktop
    privileged: true
    cgroup: host
    build:
      context: ./
      dockerfile: ./Dockerfile.ubuntu
      args:
        OS_VERSION: 25.04
        DESKTOP_INSTALL: "1"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  ubuntu_24_04:
    image: warpcode/molecule-ubuntu:24.04
    privileged: true
    cgroup: host
    build:
      context: ./
      dockerfile: ./Dockerfile.ubuntu
      args:
        OS_VERSION: 24.04
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  ubuntu_24_04_desktop:
    image: warpcode/molecule-ubuntu:24.04_desktop
    privileged: true
    cgroup: host
    build:
      context: ./
      dockerfile: ./Dockerfile.ubuntu
      args:
        OS_VERSION: 24.04
        DESKTOP_INSTALL: "1"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  ubuntu_22_04:
    image: warpcode/molecule-ubuntu:22.04
    privileged: true
    cgroup: host
    build:
      context: ./
      dockerfile: ./Dockerfile.ubuntu
      args:
        OS_VERSION: 22.04
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  ubuntu_22_04_desktop:
    image: warpcode/molecule-ubuntu:22.04_desktop
    privileged: true
    cgroup: host
    build:
      context: ./
      dockerfile: ./Dockerfile.ubuntu
      args:
        OS_VERSION: 22.04
        DESKTOP_INSTALL: "1"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  ubuntu_20_04:
    image: warpcode/molecule-ubuntu:20.04
    privileged: true
    cgroup: host
    build:
      context: ./
      dockerfile: ./Dockerfile.ubuntu
      args:
        OS_VERSION: 20.04
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  ubuntu_20_04_desktop:
    image: warpcode/molecule-ubuntu:20.04_desktop
    privileged: true
    cgroup: host
    build:
      context: ./
      dockerfile: ./Dockerfile.ubuntu
      args:
        OS_VERSION: 20.04
        DESKTOP_INSTALL: "1"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
