ARG OS_VERSION=latest

FROM archlinux:${OS_VERSION}

ARG DESKTOP_INSTALL=0

RUN pacman-key --init \
    && pacman -Sy --noconfirm --disable-sandbox \
        archlinux-keyring \
        openssl \
        python \
        python-pip \
        sudo \
        systemd \
        util-linux \
        $([ "$DESKTOP_INSTALL" == "1" ] && echo 'gnome'); \
        ([ "$DESKTOP_INSTALL" == "1" ] && pacman -Runs snapd pipewire alsa || true);

RUN rm -rf /lib/systemd/system/systemd*udev*; \
    rm -rf /lib/systemd/system/getty.target; \
    rm -rf /usr/lib/python3.12/EXTERNALLY-MANAGED; \
    locale-gen en_US.UTF-8; \
    ([ "$DESKTOP_INSTALL" == "1" ] && systemctl stop gdm.service || true); \
    ([ "$DESKTOP_INSTALL" == "1" ] && systemctl disable gdm.service || true); \
    ([ "$DESKTOP_INSTALL" == "1" ] && systemctl stop NetworkManager.service || true); \
    ([ "$DESKTOP_INSTALL" == "1" ] && systemctl disable NetworkManager.service || true);

# Install ansible
RUN pip install ansible

# Install Ansible inventory file.
RUN mkdir -p /etc/ansible
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

# Fake initctl to launch services
COPY initctl_faker .
RUN chmod +x initctl_faker && rm -fr /sbin/initctl && ln -s /initctl_faker /sbin/initctl

VOLUME ["/sys/fs/cgroup", "/tmp", "/run"]
CMD ["/lib/systemd/systemd"]
