ARG OS_VERSION=latest

FROM ubuntu:${OS_VERSION}

ARG DESKTOP_INSTALL="0"
ARG DEBIAN_FRONTEND=noninteractive

# Install dependencies.
RUN apt-get update \
    && apt-get install -y $([ "$DESKTOP_INSTALL" = "0" ] && echo '--no-install-recommends') \
       apt-utils \
       build-essential \
       iproute2 \
       libffi-dev \
       libssl-dev \
       libyaml-dev \
       locales \
       python3-dev \
       python3-pip \
       python3-setuptools \
       python3-yaml \
       rsyslog \
       software-properties-common \
       sudo \
       systemd \
       systemd-cron \
       $([ "${DESKTOP_INSTALL}" = "1" ] && echo 'ubuntu-desktop'); \
    apt-get remove -y snapd; \
    apt-get clean; \
    rm -Rf /var/lib/apt/lists/*; \
    rm -Rf /usr/share/doc; \
    rm -Rf /usr/share/manp; \
    rm -rf /lib/systemd/system/multi-user.target.wants/*;\
    rm -rf /etc/systemd/system/*.wants/*;\
    rm -rf /lib/systemd/system/systemd*udev*; \
    rm -rf /lib/systemd/system/getty.target; \
    rm -rf /usr/lib/python3.*/EXTERNALLY-MANAGED; \
    locale-gen en_US.UTF-8; \
    ([ "$DESKTOP_INSTALL" = "1" ] && systemctl stop gdm.service || true); \
    ([ "$DESKTOP_INSTALL" = "1" ] && systemctl disable gdm.service || true); \
    ([ "$DESKTOP_INSTALL" = "1" ] && systemctl stop NetworkManager.service || true); \
    ([ "$DESKTOP_INSTALL" = "1" ] && systemctl disable NetworkManager.service || true);

RUN sed -i 's/^\($ModLoad imklog\)/#\1/' /etc/rsyslog.conf

# Install Ansible.
RUN pip3 install ansible

COPY initctl_faker .
RUN chmod +x initctl_faker && rm -fr /sbin/initctl && ln -s /initctl_faker /sbin/initctl

# Install Ansible inventory file.
RUN mkdir -p /etc/ansible
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

VOLUME ["/sys/fs/cgroup", "/tmp", "/run"]
CMD ["/lib/systemd/systemd"]
