ARG OS_VERSION=latest

FROM archlinux:${OS_VERSION}

RUN pacman -Sy --noconfirm \
        archlinux-keyring \
        python \
        openssl \
        su \
        sudo \
        systemd \
        systemd-cron \
    && pacman -Syu --noconfirm

RUN pip install ansible

# Install Ansible inventory file.
RUN mkdir -p /etc/ansible
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

# Remove unnecessary getty and udev targets that result in high CPU usage when using
# multiple containers with Molecule (https://github.com/ansible/molecule/issues/1104)
RUN rm -f /lib/systemd/system/systemd*udev* \
  && rm -f /lib/systemd/system/getty.target

VOLUME ["/sys/fs/cgroup", "/tmp", "/run"]
CMD ["/lib/systemd/systemd"]
