ARG OS_VERSION=stable

FROM debian:${OS_VERSION}

ARG DESKTOP_INSTALL=0
ARG DEBIAN_FRONTEND=noninteractive

# Install dependencies.
RUN apt-get update \
    && apt-get install -y $([ "$DESKTOP_INSTALL" = "0" ] && echo '--no-install-recommends') \
       build-essential \
       iproute2 \
       libffi-dev \
       libssl-dev \
       procps \
       python3-apt \
       python3-dev \
       python3-pip \
       python3-setuptools \
       python3-wheel \
       sudo \
       systemd \
       systemd-sysv \
       wget \
       $([ "$DESKTOP_INSTALL" = "1" ] && echo 'task-gnome-desktop') \
    && apt-get clean \
    && rm -Rf /var/lib/apt/lists/* \
    && rm -Rf /usr/share/doc && rm -Rf /usr/share/man \
    && rm -rf /lib/systemd/system/multi-user.target.wants/getty.target \
    && rm -rf /usr/lib/python3.*/EXTERNALLY-MANAGED; \
    ([ "$DESKTOP_INSTALL" = "1" ] && systemctl stop gdm.service || true); \
    ([ "$DESKTOP_INSTALL" = "1" ] && systemctl disable gdm.service || true);

# Install Ansible.
RUN pip3 install --upgrade pip
RUN pip3 install ansible cryptography

COPY initctl_faker .
RUN chmod +x initctl_faker && rm -fr /sbin/initctl && ln -s /initctl_faker /sbin/initctl

# Install Ansible inventory file.
RUN mkdir -p /etc/ansible
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

VOLUME ["/sys/fs/cgroup", "/tmp", "/run"]
CMD ["/lib/systemd/systemd"]
