---
services:
  archlinux_latest:
    privileged: true
    cgroup: host
    build:
      context: ./
      image: warpcode/molecule-archlinux:latest
      dockerfile: ./Dockerfile.archlinux
      args:
          OS_VERSION: latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  debian_stable:
    privileged: true
    cgroup: host
    build:
      context: ./
      image: warpcode/molecule-debian:stable
      dockerfile: ./Dockerfile.debian
      args:
          OS_VERSION: stable
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  debian_unstable:
    privileged: true
    cgroup: host
    build:
      context: ./
      image: warpcode/molecule-debian:unstable
      dockerfile: ./Dockerfile.debian
      args:
          OS_VERSION: unstable
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  debian_12:
    privileged: true
    cgroup: host
    build:
      context: ./
      image: warpcode/molecule-debian:12
      dockerfile: ./Dockerfile.debian
      args:
          OS_VERSION: 12
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  debian_11:
    privileged: true
    cgroup: host
    build:
      context: ./
      image: warpcode/molecule-debian:11
      dockerfile: ./Dockerfile.debian
      args:
          OS_VERSION: 11
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  fedora_latest:
    privileged: true
    cgroup: host
    build:
      context: ./
      image: warpcode/molecule-fedora:latest
      dockerfile: ./Dockerfile.fedora
      args:
          OS_VERSION: latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  fedora_41:
    privileged: true
    cgroup: host
    build:
      context: ./
      image: warpcode/molecule-fedora:41
      dockerfile: ./Dockerfile.fedora
      args:
          OS_VERSION: 41
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  fedora_40:
    privileged: true
    cgroup: host
    build:
      context: ./
      image: warpcode/molecule-fedora:40
      dockerfile: ./Dockerfile.fedora
      args:
          OS_VERSION: 40
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  ubuntu_latest:
    privileged: true
    cgroup: host
    build:
      context: ./
      image: warpcode/molecule-ubuntu:latest
      dockerfile: ./Dockerfile.ubuntu
      args:
          OS_VERSION: latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  ubuntu_24_04:
    privileged: true
    cgroup: host
    build:
      context: ./
      image: warpcode/molecule-ubuntu:24.04
      dockerfile: ./Dockerfile.ubuntu
      args:
          OS_VERSION: 24.04
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  ubuntu_22_04:
    privileged: true
    cgroup: host
    build:
      context: ./
      image: warpcode/molecule-ubuntu:22.04
      dockerfile: ./Dockerfile.ubuntu
      args:
          OS_VERSION: 22.04
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  ubuntu_20_04:
    privileged: true
    cgroup: host
    build:
      context: ./
      image: warpcode/molecule-ubuntu:20.04
      dockerfile: ./Dockerfile.ubuntu
      args:
          OS_VERSION: 20.04
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
