---
name: CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "Dockerfile.*"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ci.yml"
      - "Dockerfile.*"
  schedule:
    # Run on the first of the month at 7am
    - cron: "0 7 1 * *"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Build via docker compose
        run: >
          docker compose build --no-cache

      - name: Login to DockerHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push via docker compose
        run: >
          docker compose build --push
