---
name: CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "Dockerfile.*"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ci.yml"
      - "Dockerfile.*"
  schedule:
    - cron: "0 1 * * 0"

defaults:
  run:
    working-directory: "warpcode.molecule-docker"

env:
  WORKING_DIR: "warpcode.molecule-docker"

jobs:
  build:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dockerfile:
          - name: archlinux
            docker_repo: warpcode/molecule-archlinux
            platforms: linux/amd64,linux/arm64
            version: latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: "warpcode.molecule-docker"

      - name: Install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest

      - name: Setup docker buildx
        run: |
          docker buildx create --name="${WORKING_DIR}" --platform="linux/amd64,linux/arm/v7,linux/arm64"
          docker buildx use "${WORKING_DIR}"
          docker buildx inspect --bootstrap

      - name: Build the image
        run: >
          docker buildx build
          --pull
          -f "Dockerfile.${{ matrix.dockerfile.name }}"
          -t "${{ matrix.dockerfile.docker_repo }}:${{ matrix.dockerfile.version }}"
          --platform="${{ matrix.dockerfile.platforms }}"
          --build-arg OS_VERSION="${{ matrix.dockerfile.version }}"
          .

      # - name: Check if files were changed in the roles
      #   id: changed-files
      #   uses: tj-actions/changed-files@v45
      #   with:
      #     path: "warpcode.personal-computer"
      #     dir_names_max_depth: 2
      #     dir_names: "true"
      #     write_output_files: true
      #     files: |
      #       roles/**
      #       molecule/**

      # - name: Changed Molecule test
      #   # if: steps.changed-files.outputs.any_modified == 'true'
      #   run: |
      #     . venv/bin/activate
      #     CHANGED=$(cat "../.github/outputs/all_modified_files.txt" | tr " " "\n" | xargs -I {} basename {} | uniq | sort | tr "\n" " ")
      #     if [ -d "molecule/$SCENARIO" ];then
      #       if [[ "${{ steps.changed-files.outputs.any_modified }}" == "true" ]];then
      #           if [[ $CHANGED =~ (^|[[:space:]])${SCENARIO}($|[[:space:]]) ]]; then
      #             molecule test -s "$SCENARIO"
      #           else
      #             echo "No changed files for $SCENARIO: Skipping"
      #           fi
      #       else
      #         molecule test -s "$SCENARIO"
      #       fi
      #     else
      #       echo "No tests for $SCENARIO"
      #     fi
      #   env:
      #     PY_COLORS: "1"
      #     ANSIBLE_FORCE_COLOR: "1"
      #     SCENARIO: ${{ matrix.scenario }}
      #     MOLECULE_NAME: ${{ matrix.distro.host }}
      #     MOLECULE_DOCKER_IMAGE: ${{ matrix.distro.image }}
      #     MOLECULE_DOCKER_IMAGE_PREBUILT: ${{ matrix.distro.image_prebuilt }}
      #     MOLECULE_DOCKER_CMD: ${{ matrix.distro.image_cmd }}
