---
name: CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "Dockerfile.*"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ci.yml"
      - "Dockerfile.*"
  schedule:
    - cron: "0 1 * * 0"

defaults:
  run:
    working-directory: "warpcode.molecule-docker"

env:
  WORKING_DIR: "warpcode.molecule-docker"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dockerfile:
          - name: archlinux
            docker_repo: warpcode/molecule-archlinux
            version: latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: "warpcode.molecule-docker"
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Test Build the image.
        uses: docker/build-push-action@v2
        with:
          context: ./warpcode.molecule-docker
          file: Dockerfile.${{ matrix.dockerfile.name }}
          platforms: linux/amd64
          push: false
          tags: ${{ matrix.dockerfile.docker_repo }}:${{ matrix.dockerfile.version }}
          build-args: |
            OS_VERSION=${{ matrix.dockerfile.version }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: ./warpcode.molecule-docker
          file: Dockerfile.${{ matrix.dockerfile.name }}
          platforms: linux/amd64
          push: true
          tags: ${{ matrix.dockerfile.docker_repo }}:${{ matrix.dockerfile.version }}
          build-args: |
            OS_VERSION=${{ matrix.dockerfile.version }}
