---
name: CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "Dockerfile.*"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ci.yml"
      - "Dockerfile.*"
  schedule:
    - cron: "0 1 * * 0"

defaults:
  run:
    working-directory: "warpcode.molecule-docker"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dockerfile:
          - name: archlinux
            docker_repo: warpcode/molecule-archlinux
            version: latest
          - name: debian
            docker_repo: warpcode/molecule-debian
            version: stable
          - name: debian
            docker_repo: warpcode/molecule-debian
            version: unstable
          - name: debian
            docker_repo: warpcode/molecule-debian
            version: 12
          - name: debian
            docker_repo: warpcode/molecule-debian
            version: 11
          - name: fedora
            docker_repo: warpcode/molecule-fedora
            version: latest
          - name: fedora
            docker_repo: warpcode/molecule-fedora
            version: 41
          - name: fedora
            docker_repo: warpcode/molecule-fedora
            version: 40
          - name: ubuntu
            docker_repo: warpcode/molecule-ubuntu
            version: latest
          - name: ubuntu
            docker_repo: warpcode/molecule-ubuntu
            version: 24.04
          - name: ubuntu
            docker_repo: warpcode/molecule-ubuntu
            version: 22.04
          - name: ubuntu
            docker_repo: warpcode/molecule-ubuntu
            version: 20.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test Build the image.
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile.${{ matrix.dockerfile.name }}
          platforms: linux/amd64
          push: false
          tags: ${{ matrix.dockerfile.docker_repo }}:${{ matrix.dockerfile.version }}
          build-args: |
            OS_VERSION=${{ matrix.dockerfile.version }}

      - name: Run the built image.
        run: >-
          docker run --name test-container -d --privileged
          -v /sys/fs/cgroup:/sys/fs/cgroup:rw --cgroupns=host
          ${{ matrix.dockerfile.docker_repo }}:${{ matrix.dockerfile.version }}

      - name: Verify Ansible is accessible in the built image.
        run: docker exec --tty test-container env TERM=xterm ansible --version


      - name: Login to DockerHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile.${{ matrix.dockerfile.name }}
          platforms: linux/amd64
          push: true
          tags: ${{ matrix.dockerfile.docker_repo }}:${{ matrix.dockerfile.version }}
          build-args: |
            OS_VERSION=${{ matrix.dockerfile.version }}
